### ISSUE TITLE
As of now, how to obtain the decrypted files?

### ISSUE THREAD

**Issue by darkyzhou** [kiraYuukiAsuna/Honkai-Impact-3rd-AudioTextExtractionTool#1]
Hi, I'm pretty sure we are to do the same thing.

But problems arise after I tried to extract the game resources, it seems that your tool requires some `.json` files that the extractor I am currently using won't populate. Is it because the game's sturcture has changed since then or I'm actually using the wrong tool?

Any help will be appreciated!

**Comment by kiraYuukiAsuna** [comment]
For CN version, in directory `C:\Users\{YOUR_USER_NAME}\AppData\LocalLow\miHoYo\崩坏3\Data\data `contains some `*.unity3d` files which has been encrypted using an xor key or something else i forgot. In these `*. unity3d` files contain some Text Asset, settings, Lua script, etc. What we need are these Text Asset(contain audio text, audio filename fnv1 hash string, etc. most of them are Json files after extracted). Actually, i haven't try to extract these files by myself. I use other's tool to get these files. But it's been a while since I paid attention to this. So idk what’s going on now. I looked at the current files' in CN version 7.3 and guess the sturcture may remain the same. What tool you are using? Maybe you can try another tool? 

I'm glad to help if you need more information.

**Comment by darkyzhou** [comment]
Thank you for replying!

The tool I'm using is raztools/studio, and it did extracted some TextAsset files in `.json` but I couldn't find the relevant ones. I used `ripgrep` to search for keywords like `AvatarId` and `AudioId` but got nothing. Are there any other tools that can handle HI3?

**Comment by kiraYuukiAsuna** [comment]
I checked the repo that i used before and found all of them has been deleted. So sorry i cannot provide you with the working tool. But i can share your with the CN game version v6.7 files decrypted extracted and tool that i used before. idk if v6.7 will help or not. v6.7 is enough for me so i didn't try the new version after that lol.

File download link: https://storage.kirayuukiasuna.cloud/s/8Jfq

**Comment by darkyzhou** [comment]
Thank you, I did some investigations with your files and had following discoveries:

- In the latest version of HI3, the combined size of all the `.unity3d` files under `LocalLow/.../Data` seems to decrease from over 400MB in your archive to ~234MB on my computer, which may indicates the fact that the files I am looking for might be moved away. EDIT: I found that the additional size comes from `TextMap` and `RandomDialogData` files in other languages. Maybe your client is a global one, and clients for different region might need different xor keys to be decrypted with.
- Most of the `.wav` files extracted from `.pck` files had their hash codes changed. I ran the `AudioExtract` function of your program and found that the populated `FinalMap.json` only contains the dialogs from `DLC2`.

Well, I think I get stuck here. I might need to either find out where did the files go or request your `.wav` files extracted from a version 6.7 client...

Thank you again for your help. Would you like to share your Discord, QQ or other contacts? You can send me via my email me@zqy.io if you don't want it to be public.

**Comment by kiraYuukiAsuna** [comment]
Hi! I sent an email to you. You can check your mailbox.
